version: "3.9"

services:
  kong:
    image: kong:3.7
    container_name: kong
    depends_on:
      - echo
    ports:
      - "8000:8000"  # proxy
      - "8001:8001"  # admin api
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_LOG_LEVEL: info
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./config/kong.yml:/etc/kong/kong.yml:ro
    networks:
      - kong-net

  echo:
    image: ealen/echo-server:0.9.1
    container_name: echo
    environment:
      ENABLE__ENV: "true"
    ports:
      - "8080:80"
    networks:
      - kong-net

  # Stubs for Phase 4 (monitoring). Left disabled by default.
  # prometheus:
  #   image: prom/prometheus:v2.54.1
  #   volumes:
  #     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - kong-net

  # grafana:
  #   image: grafana/grafana:10.4.3
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - kong-net

networks:
  kong-net:
    driver: bridge